FileSizeLimitKb: !!int 51200
ArchiveDepthLimit: !!int 20
ProcessingTimeLimitMs: !!int 6000000
FilesCountLimit: !!int 200
DangerousThreshold: !!int 100
YaraRuleScoreDefault: !!int 100
ScanArchives: !!bool true
FastScan: !!bool true
ArchiveFileTypes:
 - "*.7z"
 - "*.ar"
 - "*.arj"
 - "*.bz2"
 - "*.bzip2"
 - "*.cab"
 - "*.chm"
 - "*.cpio"
 - "*.cramfs"
 - "*.dmg"
 - "*.ext"
 - "*.fat"
 - "*.gpt"
 - "*.gz"
 - "*.gzip"
 - "*.hfs"
 - "*.ihex"
 - "*.iso"
 - "*.lzh"
 - "*.lzma"
 - "*.mbr"
 - "*.msi"
 - "*.nsis"
 - "*.ntfs"
 - "*.qcow2"
 - "*.rar"
 - "*.rpm"
 - "*.squashfs"
 - "*.tar"
 - "*.udf"
 - "*.uefi"
 - "*.vdi"
 - "*.vhd"
 - "*.vmdk"
 - "*.wim"
 - "*.xar"
 - "*.xz"
 - "*.z"
 - "*.zip"
ExecutableExtensions: 
 - "*.bat"
 - "*.bin"
 - "*.chm"
 - "*.cmd"
 - "*.com"
 - "*.cpl"
 - "*.dqy"
 - "*.exe"
 - "*.gadget"
 - "*.hta"
 - "*.img"
 - "*.inf1"
 - "*.ins"
 - "*.inx"
 - "*.iqy"
 - "*.isu"
 - "*.jnt"
 - "*.job"
 - "*.js"
 - "*.jse"
 - "*.lnk"
 - "*.msc"
 - "*.msi"
 - "*.msp"
 - "*.mst"
 - "*.oqy"
 - "*.paf"
 - "*.pif"
 - "*.ps1"
 - "*.reg"
 - "*.rgs"
 - "*.rqy"
 - "*.scr"
 - "*.sct"
 - "*.shb"
 - "*.shs"
 - "*.u3p"
 - "*.url"
 - "*.vb"
 - "*.vbe"
 - "*.vbs"
 - "*.vbscript"
 - "*.wpl"
 - "*.ws"
 - "*.wsc"
 - "*.wsf"
 - "*.wsh"