FileSizeLimit: !!int 20480
ArchiveDepthLimit: !!int 100
ProcessingTimeLimitMs: !!int 300
ScanArchives: !!bool true
FastScan: !!bool true
ArchiveFileTypes:
  - "*.7z"
  - "*.ar"
  - "*.arj"
  - "*.bz2"
  - "*.bzip2"
  - "*.cab"
  - "*.chm"
  - "*.cpio"
  - "*.cramfs"
  - "*.dmg"
  - "*.ext"
  - "*.fat"
  - "*.gpt"
  - "*.gz"
  - "*.gzip"
  - "*.hfs"
  - "*.ihex"
  - "*.iso"
  - "*.lzh"
  - "*.lzma"
  - "*.mbr"
  - "*.msi"
  - "*.nsis"
  - "*.ntfs"
  - "*.qcow2"
  - "*.rar"
  - "*.rpm"
  - "*.squashfs"
  - "*.tar"
  - "*.udf"
  - "*.uefi"
  - "*.vdi"
  - "*.vhd"
  - "*.vmdk"
  - "*.wim"
  - "*.xar"
  - "*.xz"
  - "*.z"
  - "*.zip"